/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'
import { Route as DocumentsSlugRouteImport } from './routes/documents.$slug'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DocumentsSlugEditRouteImport } from './routes/documents.$slug.edit'
import { Route as ApiV1OpenapiJsonRouteImport } from './routes/api/v1/openapi.json'
import { Route as ApiV1CliTagsRouteImport } from './routes/api/v1/cli/tags'
import { Route as ApiV1CliSpacesRouteImport } from './routes/api/v1/cli/spaces'
import { Route as ApiV1CliDocumentsRouteImport } from './routes/api/v1/cli/documents'
import { Route as ApiV1CliDocumentsSlugRouteImport } from './routes/api/v1/cli/documents.$slug'
import { Route as ApiV1CliAuthWhoamiRouteImport } from './routes/api/v1/cli/auth/whoami'
import { Route as ApiV1CliAuthLogoutRouteImport } from './routes/api/v1/cli/auth/logout'
import { Route as ApiV1CliAuthLoginRouteImport } from './routes/api/v1/cli/auth/login'
import { Route as ApiV1CliSpacesSpaceIdCategoriesRouteImport } from './routes/api/v1/cli/spaces.$spaceId.categories'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsSlugRoute = DocumentsSlugRouteImport.update({
  id: '/documents/$slug',
  path: '/documents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsSlugEditRoute = DocumentsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DocumentsSlugRoute,
} as any)
const ApiV1OpenapiJsonRoute = ApiV1OpenapiJsonRouteImport.update({
  id: '/api/v1/openapi/json',
  path: '/api/v1/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CliTagsRoute = ApiV1CliTagsRouteImport.update({
  id: '/api/v1/cli/tags',
  path: '/api/v1/cli/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CliSpacesRoute = ApiV1CliSpacesRouteImport.update({
  id: '/api/v1/cli/spaces',
  path: '/api/v1/cli/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CliDocumentsRoute = ApiV1CliDocumentsRouteImport.update({
  id: '/api/v1/cli/documents',
  path: '/api/v1/cli/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CliDocumentsSlugRoute = ApiV1CliDocumentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiV1CliDocumentsRoute,
} as any)
const ApiV1CliAuthWhoamiRoute = ApiV1CliAuthWhoamiRouteImport.update({
  id: '/api/v1/cli/auth/whoami',
  path: '/api/v1/cli/auth/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CliAuthLogoutRoute = ApiV1CliAuthLogoutRouteImport.update({
  id: '/api/v1/cli/auth/logout',
  path: '/api/v1/cli/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CliAuthLoginRoute = ApiV1CliAuthLoginRouteImport.update({
  id: '/api/v1/cli/auth/login',
  path: '/api/v1/cli/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CliSpacesSpaceIdCategoriesRoute =
  ApiV1CliSpacesSpaceIdCategoriesRouteImport.update({
    id: '/$spaceId/categories',
    path: '/$spaceId/categories',
    getParentRoute: () => ApiV1CliSpacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/login': typeof AuthLoginRoute
  '/documents/$slug': typeof DocumentsSlugRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/documents/$slug/edit': typeof DocumentsSlugEditRoute
  '/api/v1/cli/documents': typeof ApiV1CliDocumentsRouteWithChildren
  '/api/v1/cli/spaces': typeof ApiV1CliSpacesRouteWithChildren
  '/api/v1/cli/tags': typeof ApiV1CliTagsRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
  '/api/v1/cli/auth/login': typeof ApiV1CliAuthLoginRoute
  '/api/v1/cli/auth/logout': typeof ApiV1CliAuthLogoutRoute
  '/api/v1/cli/auth/whoami': typeof ApiV1CliAuthWhoamiRoute
  '/api/v1/cli/documents/$slug': typeof ApiV1CliDocumentsSlugRoute
  '/api/v1/cli/spaces/$spaceId/categories': typeof ApiV1CliSpacesSpaceIdCategoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/login': typeof AuthLoginRoute
  '/documents/$slug': typeof DocumentsSlugRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/documents/$slug/edit': typeof DocumentsSlugEditRoute
  '/api/v1/cli/documents': typeof ApiV1CliDocumentsRouteWithChildren
  '/api/v1/cli/spaces': typeof ApiV1CliSpacesRouteWithChildren
  '/api/v1/cli/tags': typeof ApiV1CliTagsRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
  '/api/v1/cli/auth/login': typeof ApiV1CliAuthLoginRoute
  '/api/v1/cli/auth/logout': typeof ApiV1CliAuthLogoutRoute
  '/api/v1/cli/auth/whoami': typeof ApiV1CliAuthWhoamiRoute
  '/api/v1/cli/documents/$slug': typeof ApiV1CliDocumentsSlugRoute
  '/api/v1/cli/spaces/$spaceId/categories': typeof ApiV1CliSpacesSpaceIdCategoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/login': typeof AuthLoginRoute
  '/documents/$slug': typeof DocumentsSlugRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/documents/$slug/edit': typeof DocumentsSlugEditRoute
  '/api/v1/cli/documents': typeof ApiV1CliDocumentsRouteWithChildren
  '/api/v1/cli/spaces': typeof ApiV1CliSpacesRouteWithChildren
  '/api/v1/cli/tags': typeof ApiV1CliTagsRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
  '/api/v1/cli/auth/login': typeof ApiV1CliAuthLoginRoute
  '/api/v1/cli/auth/logout': typeof ApiV1CliAuthLogoutRoute
  '/api/v1/cli/auth/whoami': typeof ApiV1CliAuthWhoamiRoute
  '/api/v1/cli/documents/$slug': typeof ApiV1CliDocumentsSlugRoute
  '/api/v1/cli/spaces/$spaceId/categories': typeof ApiV1CliSpacesSpaceIdCategoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/auth/login'
    | '/documents/$slug'
    | '/documents/new'
    | '/spaces/$slug'
    | '/tags/$slug'
    | '/documents/$slug/edit'
    | '/api/v1/cli/documents'
    | '/api/v1/cli/spaces'
    | '/api/v1/cli/tags'
    | '/api/v1/openapi/json'
    | '/api/v1/cli/auth/login'
    | '/api/v1/cli/auth/logout'
    | '/api/v1/cli/auth/whoami'
    | '/api/v1/cli/documents/$slug'
    | '/api/v1/cli/spaces/$spaceId/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/auth/login'
    | '/documents/$slug'
    | '/documents/new'
    | '/spaces/$slug'
    | '/tags/$slug'
    | '/documents/$slug/edit'
    | '/api/v1/cli/documents'
    | '/api/v1/cli/spaces'
    | '/api/v1/cli/tags'
    | '/api/v1/openapi/json'
    | '/api/v1/cli/auth/login'
    | '/api/v1/cli/auth/logout'
    | '/api/v1/cli/auth/whoami'
    | '/api/v1/cli/documents/$slug'
    | '/api/v1/cli/spaces/$spaceId/categories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/auth/login'
    | '/documents/$slug'
    | '/documents/new'
    | '/spaces/$slug'
    | '/tags/$slug'
    | '/documents/$slug/edit'
    | '/api/v1/cli/documents'
    | '/api/v1/cli/spaces'
    | '/api/v1/cli/tags'
    | '/api/v1/openapi/json'
    | '/api/v1/cli/auth/login'
    | '/api/v1/cli/auth/logout'
    | '/api/v1/cli/auth/whoami'
    | '/api/v1/cli/documents/$slug'
    | '/api/v1/cli/spaces/$spaceId/categories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DocumentsSlugRoute: typeof DocumentsSlugRouteWithChildren
  DocumentsNewRoute: typeof DocumentsNewRoute
  SpacesSlugRoute: typeof SpacesSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
  ApiV1CliDocumentsRoute: typeof ApiV1CliDocumentsRouteWithChildren
  ApiV1CliSpacesRoute: typeof ApiV1CliSpacesRouteWithChildren
  ApiV1CliTagsRoute: typeof ApiV1CliTagsRoute
  ApiV1OpenapiJsonRoute: typeof ApiV1OpenapiJsonRoute
  ApiV1CliAuthLoginRoute: typeof ApiV1CliAuthLoginRoute
  ApiV1CliAuthLogoutRoute: typeof ApiV1CliAuthLogoutRoute
  ApiV1CliAuthWhoamiRoute: typeof ApiV1CliAuthWhoamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$slug': {
      id: '/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/documents/$slug'
      preLoaderRoute: typeof DocumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$slug/edit': {
      id: '/documents/$slug/edit'
      path: '/edit'
      fullPath: '/documents/$slug/edit'
      preLoaderRoute: typeof DocumentsSlugEditRouteImport
      parentRoute: typeof DocumentsSlugRoute
    }
    '/api/v1/openapi/json': {
      id: '/api/v1/openapi/json'
      path: '/api/v1/openapi/json'
      fullPath: '/api/v1/openapi/json'
      preLoaderRoute: typeof ApiV1OpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli/tags': {
      id: '/api/v1/cli/tags'
      path: '/api/v1/cli/tags'
      fullPath: '/api/v1/cli/tags'
      preLoaderRoute: typeof ApiV1CliTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli/spaces': {
      id: '/api/v1/cli/spaces'
      path: '/api/v1/cli/spaces'
      fullPath: '/api/v1/cli/spaces'
      preLoaderRoute: typeof ApiV1CliSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli/documents': {
      id: '/api/v1/cli/documents'
      path: '/api/v1/cli/documents'
      fullPath: '/api/v1/cli/documents'
      preLoaderRoute: typeof ApiV1CliDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli/documents/$slug': {
      id: '/api/v1/cli/documents/$slug'
      path: '/$slug'
      fullPath: '/api/v1/cli/documents/$slug'
      preLoaderRoute: typeof ApiV1CliDocumentsSlugRouteImport
      parentRoute: typeof ApiV1CliDocumentsRoute
    }
    '/api/v1/cli/auth/whoami': {
      id: '/api/v1/cli/auth/whoami'
      path: '/api/v1/cli/auth/whoami'
      fullPath: '/api/v1/cli/auth/whoami'
      preLoaderRoute: typeof ApiV1CliAuthWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli/auth/logout': {
      id: '/api/v1/cli/auth/logout'
      path: '/api/v1/cli/auth/logout'
      fullPath: '/api/v1/cli/auth/logout'
      preLoaderRoute: typeof ApiV1CliAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli/auth/login': {
      id: '/api/v1/cli/auth/login'
      path: '/api/v1/cli/auth/login'
      fullPath: '/api/v1/cli/auth/login'
      preLoaderRoute: typeof ApiV1CliAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli/spaces/$spaceId/categories': {
      id: '/api/v1/cli/spaces/$spaceId/categories'
      path: '/$spaceId/categories'
      fullPath: '/api/v1/cli/spaces/$spaceId/categories'
      preLoaderRoute: typeof ApiV1CliSpacesSpaceIdCategoriesRouteImport
      parentRoute: typeof ApiV1CliSpacesRoute
    }
  }
}

interface DocumentsSlugRouteChildren {
  DocumentsSlugEditRoute: typeof DocumentsSlugEditRoute
}

const DocumentsSlugRouteChildren: DocumentsSlugRouteChildren = {
  DocumentsSlugEditRoute: DocumentsSlugEditRoute,
}

const DocumentsSlugRouteWithChildren = DocumentsSlugRoute._addFileChildren(
  DocumentsSlugRouteChildren,
)

interface ApiV1CliDocumentsRouteChildren {
  ApiV1CliDocumentsSlugRoute: typeof ApiV1CliDocumentsSlugRoute
}

const ApiV1CliDocumentsRouteChildren: ApiV1CliDocumentsRouteChildren = {
  ApiV1CliDocumentsSlugRoute: ApiV1CliDocumentsSlugRoute,
}

const ApiV1CliDocumentsRouteWithChildren =
  ApiV1CliDocumentsRoute._addFileChildren(ApiV1CliDocumentsRouteChildren)

interface ApiV1CliSpacesRouteChildren {
  ApiV1CliSpacesSpaceIdCategoriesRoute: typeof ApiV1CliSpacesSpaceIdCategoriesRoute
}

const ApiV1CliSpacesRouteChildren: ApiV1CliSpacesRouteChildren = {
  ApiV1CliSpacesSpaceIdCategoriesRoute: ApiV1CliSpacesSpaceIdCategoriesRoute,
}

const ApiV1CliSpacesRouteWithChildren = ApiV1CliSpacesRoute._addFileChildren(
  ApiV1CliSpacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthLoginRoute: AuthLoginRoute,
  DocumentsSlugRoute: DocumentsSlugRouteWithChildren,
  DocumentsNewRoute: DocumentsNewRoute,
  SpacesSlugRoute: SpacesSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
  ApiV1CliDocumentsRoute: ApiV1CliDocumentsRouteWithChildren,
  ApiV1CliSpacesRoute: ApiV1CliSpacesRouteWithChildren,
  ApiV1CliTagsRoute: ApiV1CliTagsRoute,
  ApiV1OpenapiJsonRoute: ApiV1OpenapiJsonRoute,
  ApiV1CliAuthLoginRoute: ApiV1CliAuthLoginRoute,
  ApiV1CliAuthLogoutRoute: ApiV1CliAuthLogoutRoute,
  ApiV1CliAuthWhoamiRoute: ApiV1CliAuthWhoamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
