/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'
import { Route as DocumentsSlugRouteImport } from './routes/documents.$slug'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DocumentsSlugEditRouteImport } from './routes/documents.$slug.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsSlugRoute = DocumentsSlugRouteImport.update({
  id: '/documents/$slug',
  path: '/documents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsSlugEditRoute = DocumentsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DocumentsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/login': typeof AuthLoginRoute
  '/documents/$slug': typeof DocumentsSlugRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/documents/$slug/edit': typeof DocumentsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/login': typeof AuthLoginRoute
  '/documents/$slug': typeof DocumentsSlugRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/documents/$slug/edit': typeof DocumentsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/login': typeof AuthLoginRoute
  '/documents/$slug': typeof DocumentsSlugRouteWithChildren
  '/documents/new': typeof DocumentsNewRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/documents/$slug/edit': typeof DocumentsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/auth/login'
    | '/documents/$slug'
    | '/documents/new'
    | '/spaces/$slug'
    | '/tags/$slug'
    | '/documents/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/auth/login'
    | '/documents/$slug'
    | '/documents/new'
    | '/spaces/$slug'
    | '/tags/$slug'
    | '/documents/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/auth/login'
    | '/documents/$slug'
    | '/documents/new'
    | '/spaces/$slug'
    | '/tags/$slug'
    | '/documents/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DocumentsSlugRoute: typeof DocumentsSlugRouteWithChildren
  DocumentsNewRoute: typeof DocumentsNewRoute
  SpacesSlugRoute: typeof SpacesSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$slug': {
      id: '/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/documents/$slug'
      preLoaderRoute: typeof DocumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$slug/edit': {
      id: '/documents/$slug/edit'
      path: '/edit'
      fullPath: '/documents/$slug/edit'
      preLoaderRoute: typeof DocumentsSlugEditRouteImport
      parentRoute: typeof DocumentsSlugRoute
    }
  }
}

interface DocumentsSlugRouteChildren {
  DocumentsSlugEditRoute: typeof DocumentsSlugEditRoute
}

const DocumentsSlugRouteChildren: DocumentsSlugRouteChildren = {
  DocumentsSlugEditRoute: DocumentsSlugEditRoute,
}

const DocumentsSlugRouteWithChildren = DocumentsSlugRoute._addFileChildren(
  DocumentsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthLoginRoute: AuthLoginRoute,
  DocumentsSlugRoute: DocumentsSlugRouteWithChildren,
  DocumentsNewRoute: DocumentsNewRoute,
  SpacesSlugRoute: SpacesSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
